# Generated by Django 5.2.4 on 2026-04-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsetting',
            name='business',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='key',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='value',
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='allow_multi_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='allow_self_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='audit_log_level',
            field=models.CharField(choices=[('minimal', 'Minimal'), ('detailed', 'Detailed')], default='detailed', max_length=10),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='audit_retention_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='auto_disable_inactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='beer_density',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='default_keg_weight',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='enable_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='enable_audit_logs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='enable_email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='enable_keg_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='enable_pos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='enable_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='force_password_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='force_role_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='lock_system_roles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='max_staff_per_business',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='notify_keg_loss',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='notify_low_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='notify_suspicious_activity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='session_timeout',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='system_name',
            field=models.CharField(default='KEGTRACK', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='theme_color',
            field=models.CharField(default='#4F46E5', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='track_login_meta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='trial_days',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='volume_unit',
            field=models.CharField(choices=[('L', 'Litres'), ('ML', 'Millilitres')], default='L', max_length=5),
        ),
    ]
