# Generated by Django 5.2.4 on 2026-04-24 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationpoint',
            options={'ordering': ['type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product', 'volume']},
        ),
        migrations.AlterModelOptions(
            name='stockatlocation',
            options={'ordering': ['location']},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.productcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'volume')},
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
