# Generated by Django 5.2.4 on 2026-04-25 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_locationpoint_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='unit_price',
        ),
    ]
