# Generated by Django 5.2.4 on 2026-04-27 12:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_businessproductprice_options_and_more'),
        ('inventory', '0003_remove_productvariant_unit_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockatlocation',
            options={'ordering': ['location', 'variant']},
        ),
        migrations.AddField(
            model_name='locationpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationpoint',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationpoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockatlocation',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='locationpoint',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='business.business'),
        ),
        migrations.AlterField(
            model_name='stockatlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.locationpoint'),
        ),
        migrations.AlterField(
            model_name='stockatlocation',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_stock', to='inventory.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='locationpoint',
            unique_together={('business', 'name')},
        ),
    ]
