# Generated by Django 5.2.4 on 2026-04-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_businessproductprice_options_and_more'),
        ('inventory', '0004_alter_stockatlocation_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locationpoint',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stockatlocation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='locationpoint',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_location_per_business'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'volume'), name='unique_product_variant'),
        ),
        migrations.AddConstraint(
            model_name='stockatlocation',
            constraint=models.UniqueConstraint(fields=('location', 'variant'), name='unique_stock_per_location'),
        ),
    ]
