# Generated by Django 5.2.4 on 2026-05-01 16:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stockmovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockatlocation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
