# Generated by Django 5.2.4 on 2026-04-27 12:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_superadmin'),
        ('business', '0003_businessstaff'),
        ('inventory', '0003_remove_productvariant_unit_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessproductprice',
            options={'ordering': ['business', 'variant']},
        ),
        migrations.AlterModelOptions(
            name='businessstaff',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='businessproductprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessproductprice',
            name='currency',
            field=models.CharField(default='KES', max_length=10),
        ),
        migrations.AddField(
            model_name='businessproductprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='businessstaff',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_invited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessstaff',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessstaff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='businessproductprice',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='business.business'),
        ),
        migrations.AlterField(
            model_name='businessproductprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='businessproductprice',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_prices', to='inventory.productvariant'),
        ),
        migrations.AlterField(
            model_name='businessstaff',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='business.business'),
        ),
        migrations.AlterField(
            model_name='businessstaff',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_staff_roles', to='accounts.role'),
        ),
        migrations.AlterField(
            model_name='businessstaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
