# Generated by Django 5.2.4 on 2026-04-29 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_businessproductprice_options_and_more'),
        ('inventory', '0005_alter_locationpoint_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessproductprice',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar')], default='KES', max_length=10),
        ),
        migrations.CreateModel(
            name='BusinessProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_links', to='inventory.product')),
            ],
            options={
                'unique_together': {('business', 'product')},
            },
        ),
    ]
