# Generated by Django 5.2.4 on 2026-04-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_business_deleted_at_business_is_deleted_and_more'),
        ('inventory', '0006_stockmovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproductprice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='businessproductprice',
            index=models.Index(fields=['business', 'variant'], name='business_bu_busines_323b30_idx'),
        ),
    ]
