# Generated by Django 5.2.4 on 2026-05-01 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_businessproductprice_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessProduct',
        ),
    ]
