# Generated by Django 5.2.4 on 2026-04-26 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0003_businessstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='KegSystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_keg_tracking', models.BooleanField(default=True)),
                ('force_verification', models.BooleanField(default=True)),
                ('require_photo_proof', models.BooleanField(default=True)),
                ('require_weight_check', models.BooleanField(default=True)),
                ('live_camera_only', models.BooleanField(default=True)),
                ('variance_threshold_percent', models.FloatField(default=2.0)),
                ('beer_density', models.FloatField(default=1.01)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessKegPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_keg_tracking', models.BooleanField(default=True)),
                ('max_variance_percent', models.FloatField(default=3.0)),
                ('strict_verification', models.BooleanField(default=True)),
                ('auto_lock_on_fraud', models.BooleanField(default=False)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='KegFraudSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_variance', models.FloatField(default=0)),
                ('fraud_score', models.FloatField(default=0)),
                ('flagged', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
        ),
    ]
