# Generated by Django 5.2.4 on 2026-04-26 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businessstaff'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KegType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beer_type', models.CharField(choices=[('regular', 'Regular Keg'), ('dark', 'Dark keg')], max_length=10)),
                ('capacity_litres', models.FloatField()),
                ('empty_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Keg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('keg_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.kegtype')),
            ],
        ),
        migrations.CreateModel(
            name='KegSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('expected_remaining_litres', models.FloatField(default=0)),
                ('keg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.keg')),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KegVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('shift_end', 'Shift End'), ('keg_empty', 'Keg Empty')], max_length=20)),
                ('measured_weight', models.FloatField()),
                ('calculated_litres', models.FloatField()),
                ('variance', models.FloatField()),
                ('photo', models.ImageField(upload_to='keg_verifications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.keg')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.kegsession')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
