# Generated by Django 5.2.4 on 2026-04-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_kegtype_keg_kegsession_kegverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegsession',
            name='consumed_volume',
            field=models.FloatField(default=0),
        ),
    ]
