# Generated by Django 5.2.4 on 2026-04-26 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_kegsession_consumed_volume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='kegsession',
            index=models.Index(fields=['status'], name='tracking_ke_status_16fb30_idx'),
        ),
        migrations.AddIndex(
            model_name='kegsession',
            index=models.Index(fields=['opened_at'], name='tracking_ke_opened__845cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='kegsession',
            index=models.Index(fields=['keg'], name='tracking_ke_keg_id_545e4b_idx'),
        ),
    ]
